title:  Diagnose Diabetic Retinopathy
description: Classify fundus images using artificial intelligence
about:


  Diagnose diabetic retina 


  Project by Machine Learning and Artificial Intelligence

  Developer // Zulman Arif,ST

code: google.com

sampleImages:
  - name: No Retinopathy
    url: https://i.imgur.com/bag6XaA.jpg
  - name: Mild Nonproliferative Retinopathy
    url: https://i.imgur.com/ZcLBb6b.jpg
  - name: Moderate Nonproliferative Retinopathy
    url: https://i.imgur.com/gLTumUd.jpg
  - name: Severe Nonproliferative Retinopathy
    url: https://i.imgur.com/Uw0rR4Y.jpg
  - name: Proliferative Diabetic Retinopathy
    url: https://i.imgur.com/TDUlmUa.jpg
