
title: Penguji Diabetes Retinopathy  
description: Uji fundus images dengan deep learning dan AI
about:


  Aplikasi berbasis web untuk menguji diabetes retinopathy dengan Artificial Intelligence dan Machine Learning  


  Semoga bermanfaat untuk masyarakat luas


  Developer - Zulman Arif,ST


code: id.m.wikipedia.org/wiki/retinopati_diabetes

sampleImages:
  - name: No Retinopathy
    url: https://i.imgur.com/bag6XaA.jpg
  - name: Mild Nonproliferative Retinopathy
    url: https://i.imgur.com/ZcLBb6b.jpg
  - name: Moderate Nonproliferative Retinopathy
    url: https://i.imgur.com/gLTumUd.jpg
  - name: Severe Nonproliferative Retinopathy
    url: https://i.imgur.com/Uw0rR4Y.jpg
  - name: Proliferative Diabetic Retinopathy
    url: https://i.imgur.com/TDUlmUa.jpg
