title:  Diagnose Retinopati Diabetes
description: Eye Check Artificial Intelligence by-Arif
about:


  Aplikasi online untuk Rujukan atau Referrable Diabetic Retinopathy (RDR) berdasarkan klasifikasi menggunakan kecerdasan buatan /Artificial Intelligence dan Machine Learning
  
  
  Developer // Zulman Arif, ST
  
  
  Alamat // Pabdau Jaya, Kampar Riau
  
  
  NOTE - Hasil resmi tetap merujuk pada diagnosa dokter atau tenaga ahli medis


code: https://id.wikipedia.org/wiki/Retinopati_diabetes

sampleImages:
  - name: No Retinopathy
    url: https://i.imgur.com/bag6XaA.jpg
  - name: Mild Nonproliferative Retinopathy
    url: https://i.imgur.com/ZcLBb6b.jpg
  - name: Moderate Nonproliferative Retinopathy
    url: https://i.imgur.com/gLTumUd.jpg
  - name: Severe Nonproliferative Retinopathy
    url: https://i.imgur.com/Uw0rR4Y.jpg
  - name: Proliferative Diabetic Retinopathy
    url: https://i.imgur.com/TDUlmUa.jpg
    
    
   
