
title: Diabetes Retinopati Tester  
description: Uji Fundus Image dengan AI
about:


  Aplikasi berbasis web untuk mengklasifikasi adanya indikasi Diabetes Retinopati pada penderita diabetes dengan Artificial Intelligence 


  Cara penggunaan ///
  
  
  1. Arahkan Condenser Lens ke arah retina mata 
  
  
  2. Ambil foto /image dari retina dengan kamera / melalui condenser Lens
  
  
  3. Simpan gambar dalam gallery atau penyimpanan data 
  
  
  Developer - Zulman Arif,ST
  
  
  PERHATIAN/// RUJUKAN RESMI HARUS DARI DOKTER ATAU TENAGA AHLI MEDIS 


code: https://id.m.wikipedia.org/wiki/Retinopati_diabetes

sampleImages:
  - name: No Retinopathy
    url: https://i.imgur.com/bag6XaA.jpg
  - name: Mild Nonproliferative 
    url: https://i.imgur.com/ZcLBb6b.jpg
  - name: Moderate Nonproliferative 
    url: https://i.imgur.com/gLTumUd.jpg
  - name: Severe Nonproliferative 
    url: https://i.imgur.com/Uw0rR4Y.jpg
  - name: Proliferative Diabetic 
    url: https://i.imgur.com/TDUlmUa.jpg
